### ISSUE TITLE
Blurred text

### ISSUE THREAD

**Issue by Ararana** [vasturiano/icicle-chart#5]
The text in the slices blur when the cursor moves between levels. The blur get worse the more you are zoomed in. 

This appears most prevalent in Chrome.

**Comment by vasturiano** [comment]
Thanks for this report @Ararana.

This effect seems to be an obscure rendering glitch on recent versions of webkit. Noticeable on svg elements with a high scale transform applied (deep zoom) where the opacity is transitioned between any two values via css, which is what's happening with the styling applied to the `:hover` selector.

Anyway, I've swapped it with `fill-opacity` animation and the glitch appears to be completely gone. The visual difference is minimal, mainly now the opacity change is not applied to the text but only to the rect fill.

Try it with the latest version at: https://vasturiano.github.io/icicle-chart/example/flare/

**Comment by Ararana** [comment]
That did the trick, thanks for the update!
