### ISSUE TITLE
Reset zoom on zoomed Node click

### ISSUE THREAD

**Issue by Cantasura** [vasturiano/icicle-chart#6]
Hi there,
first of all thank you very much for this framework and also for the suburst-chart 😁 👍 
I would like to be able to reset the zoom when I click the same node again (see link below).

Maybe you could create a function where the return type is the zoomed node, then we could accomplish this feature with the click method.

**Additional context**
https://observablehq.com/@d3/zoomable-icicle (something like this maybe)

Best wishes

**Comment by vasturiano** [comment]
@Cantasura thanks for reaching out.

I suppose you could do this already by tracking the clicked nodes. Something like:
```js
let lastClickedNode;

(...)

myChart.onClick(node => {
  if (node === lastClickedNode) {
    myChart.zoomReset();
  } else {
    myChart.zoomToNode(node);
  }
  lastClickedNode = node;
})
```

**Comment by Cantasura** [comment]
That's exactly what I needed, thank you very much :)
